const SearchTypes = {
  SEARCH_PRODUCTS_START: 'SEARCH_PRODUCTS_START',
  SEARCH_PRODUCTS_SUCCESS: 'SEARCH_PRODUCTS_SUCCESS',
  SEARCH_PRODUCTS_FAILURE: 'SEARCH_PRODUCTS_FAILURE',
};

export default SearchTypes;
